feat(scripts/upgrade): prompt for update if metadata cannot be found
if the latest.json cannot be found the upgrade script used to bomb. now it will prompt upgrade
instead

diff --git a/bin/upgrade b/bin/upgrade
--- a/bin/upgrade
+++ b/bin/upgrade
@@ -17,23 +17,29 @@ generate_help_docs () {
 
 update_module () {
    meta_file=themes/"$1"/data/npm/latest.json
-   current_vers=`sed -n 's/.*"version":"\([^"]*\).*/\1/p' < "$meta_file"`
-   if ! [ -f "$meta_file" ] ; then
-      echo "Error: Unable to locate metadata for $1. Cannot proceed with upgrade." >&2; exit 1
+   if [ -f "$meta_file" ] ; then
+      current_vers=`sed -n 's/.*"version":"\([^"]*\).*/\1/p' < "$meta_file"`
    else
-      LATEST_META=$(wget -qO - https://registry.npmjs.org/"$1"/latest)
-      latest_vers=`sed -n 's/.*"version":"\([^"]*\).*/\1/p' <<< "$LATEST_META"`
+      echo "Cannot detect version. Upgrade $1 anyway (y/n)? \c"
+      read answer
+      [ "$answer" = "${answer#[Yy]}" ] && exit 1
+   fi
+   LATEST_META=$(wget -qO - https://registry.npmjs.org/"$1"/latest)
+   latest_vers=`sed -n 's/.*"version":"\([^"]*\).*/\1/p' <<< "$LATEST_META"`
+   if [ "$current_vers" ] ; then
       if [ "$current_vers" = "$latest_vers" ] ; then
          echo "Did not upgrade $1. Already using latest version." >&1; exit 0
       else
-         echo "Starting upgrade from $current_vers to $latest_vers ..."
-         rm -rf themes/"$1"/*
-         wget -qO - https://registry.npmjs.org/"$1"/-/"$1"-"$latest_vers".tgz | tar --strip-components=1 -xz -C themes/"$1"
-         echo "Version $latest_vers downloaded to themes/$1"
-         [ "$1" = "after-dark" ] && generate_help_docs
-         echo "Upgrade complete! Please see CHANGELOG.md for changes."
+         echo "Upgrading $1 from $current_vers to $latest_vers ..."
       fi
+   else
+      echo "Upgrading $1 from unknown version to $latest_vers ..."
    fi
+   rm -rf themes/"$1"/* # maintains dotfiles, e.g. git and env
+   wget -qO - https://registry.npmjs.org/"$1"/-/"$1"-"$latest_vers".tgz | tar --strip-components=1 -xz -C themes/"$1"
+   echo "Version $latest_vers downloaded to themes/$1"
+   [ "$1" = "after-dark" ] && generate_help_docs
+   echo "Upgrade complete! Please see CHANGELOG.md for changes."
 }
 
 set -e
